# Generated by Django 2.1.5 on 2019-01-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0003_auto_20190121_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
